### PR TITLE
Initial Implementation

### PR DESCRIPTION
**Pull request by elmigranto**
#1

### CODE REVIEW

**Comment by elmigranto** [comment]
> **push notification**
> 
> An optional `push` field can be added in the body of the added message. If set, the content of this field will be added to the notification, but won't be stored in the room's message.

No matter what, we send notification to everyone after message is added. What is "optional `push` field", is it `req.body.push` when adding message? What do we use it for? Does it hold notification's `data`, what's "adding to notification"?

**Comment by j3k0** [comment]
Yes, no matter what, we send a notification to everyone (but the sender).

We give the option for a message to also trigger a **push** notification, by adding the `push` field.

When `req.body.push` is copied into the notification request sent to the other members of the room, they will receive a push-notification.

See https://github.com/j3k0/ganomede-notifications#notifications (documentation of the notification module, where `push` is also documented)

"adding to notification" means "copied into the request to the notification module".

Hope it's clearer?

**Comment by elmigranto** [comment]
Right, I totally forgot that notification and push notification are 2 different things.

**Comment by elmigranto** [comment]
Okay, I believe everything is in place, except some [questions on notifications](https://github.com/j3k0/ganomede-notifications/pull/22).

**Comment by elmigranto** [comment]
Updated notifications. Ready for review.

**Pull request merged**
